### ISSUE TITLE
Scraping profiles by name

### ISSUE THREAD

**Issue by ajuavinett** [federicohaag/LinkedInScraping#6]
Hi Federico, thanks for this super useful tool! I completed the configuration and came to this point:

```
Configuration completed. You can now do scraping.
To scrape profile by url: execute do_scraping.py
To search profiles by name: execute search_profiles_by_name.py
```

I'm interested in collecting data from a list of names, but it doesn't look like there is an option to do it by name yet? (As an aside, it'd be awesome if you could also restrict it to geographic area, in case of duplicate names.)

**Comment by federicohaag** [comment]
Hi, thank you for your feedback. This code is not anymore maintained so no further implementations will be done. However, any external contribution is more than welcome, and I will take time to review and eventually merge it.
