### ISSUE TITLE
Scraping profiles by hashtags

### ISSUE THREAD

**Issue by rizwanhaidar** [federicohaag/LinkedInScraping#7]
Hi 
I am Rizwan, I am working on a bot that can be used for marketing.
Phases include
1.Scraping emails of persons with specific Hashtags on their post
2.Perform automation to send emails in bulk to those people
I am working on the ist part I want to start working right aways making additions in your code.
I have tried to reach out you on LinkedIn kindly look into that please

**Comment by federicohaag** [comment]
Hi, thank you for your feedback. This code is not anymore maintained so no further implementations will be done. However, any external contribution is more than welcome, and I will take time to review and eventually merge it.
